### ISSUE TITLE
Incorrect Bing Search API URL 

### ISSUE THREAD

**Issue by Freakazoidile** [NetSPI/MicroBurst#10]
_Invoke-EnumerateAzureBlogs_ errors when searching BingAPI for containers and storage accounts because the URL and Endpoint is incorrect, or has changed. 

The issue can be fixed by modifying _Invoke-EnumerateAzureBlobs.ps1_ in the _Misc_ directory. On Line 143 the URI  needs to be updated.

Old domain: api.cognitive.microsoft.com
Old endpoint: /bing/v7.0/search

New Domain: api.bing.microsoft.com
New Endpoint: /v7.0/search

Line 143, -URI string, new value should be:
`-URI "https://api.bing.microsoft.com/v7.0/search?q=$BingQuery&count=50"`

**Comment by kfosaaen** [comment]
Fixed with this commit - https://github.com/NetSPI/MicroBurst/commit/cce95ce5dbcbd918f9bcc420baa4f6f75fe23e34
Thanks!
