### ISSUE TITLE
 System.Exception: XOpenDisplay failed

### ISSUE THREAD

**Issue by faheemadam** [NetSPI/MicroBurst#16]
how can i fix this i get the same error on export-csv

Get-AzPasswords -Verbose | Out-GridView
VERBOSE: TmFtZSRfLk5hbWU=
VERBOSE: SWQkXy5JZA==
VERBOSE: VGVuYW50SWQkXy5UZW5hbnRJZA==
VERBOSE: U3RhdGUkXy5TdGF0ZQ==

Unhandled Exception: System.TypeInitializationException: The type initializer for 'OutGridView.Application.AvaloniaAppRunner' threw an exception. ---> System.Exception: XOpenDisplay failed
   at Avalonia.X11.AvaloniaX11Platform.Initialize(X11PlatformOptions options)
   at Avalonia.Controls.AppBuilderBase`1.Setup()
   at OutGridView.Application.AvaloniaAppRunner.BuildAvaloniaApp() in D:\a\1\s\src\OutGridView.Gui\AvaloniaAppRunner.cs:line 34
   at OutGridView.Application.AvaloniaAppRunner..cctor() in D:\a\1\s\src\OutGridView.Gui\AvaloniaAppRunner.cs:line 31
   --- End of inner exception stack trace ---
   at OutGridView.Application.Program.Main(String[] args) in D:\a\1\s\src\OutGridView.Gui\Program.cs:line 26

**Comment by kfosaaen** [comment]
`how can i fix this i get the same error on export-csv`

Can you try changing the command to `Get-AzPasswords -Verbose | Export-Csv -NoTypeInformation -Path .\test.csv`?
Out-GridView will just display the table in the GUI.

I'm not sure why you're getting the Avalonia errors. Are you running this in a standard Windows PowerShell session?

**Comment by faheemadam** [comment]
Hi

Well hard to tell now, for some reason my responses are completely different.

If I execute the command it just comes back to the command promot. I ran the login command just to confirm and the steps you outlined but its not doing anything

I will have to investigate why



From: Karl Fosaaen ***@***.***>
Date: Friday, 23 July 2021 at 16:32
To: NetSPI/MicroBurst ***@***.***>
Cc: faheemadam ***@***.***>, Author ***@***.***>
Subject: Re: [NetSPI/MicroBurst] System.Exception: XOpenDisplay failed (#16)

how can i fix this i get the same error on export-csv

Can you try changing the command to Get-AzPasswords -Verbose | Export-Csv -NoTypeInformation -Path .\test.csv?
Out-GridView will just display the table in the GUI.

I'm not sure why you're getting the Avalonia errors. Are you running this in a standard Windows PowerShell session?
