### ISSUE TITLE
Get-AzurePasswords -Verbose | Out-GridView

### ISSUE THREAD

**Issue by hassan-turi** [NetSPI/MicroBurst#18]
Hello sir, I am having an error using this command "Get-AzurePasswords -Verbose | Out-GridView". 
the errors are below Please guide me through this problem. I am also having a problem with the "AzureRM [Deprecated] Functions" section the commands give me a bunch of errors.
![image](https://user-images.githubusercontent.com/87395528/134253738-004f504b-3ad5-4b23-a1a8-268ad54d6ab6.png)

**Comment by passthehashbrowns** [comment]
That error likely means that you have not imported the script. You need to navigate into the AzureRM folder and run "Import-Module MicroBurst-AzureRM.ps1".

As per the documentation, the AzureRM scripts have been deprecated and are no longer receiving support. All of their functionality has been ported over to the Az scripts, which do receive updates.
