### ISSUE TITLE
Import-Module : Could not load type 'Microsoft.Azure.Management

### ISSUE THREAD

**Issue by DarknightCanada** [NetSPI/MicroBurst#19]
When trying to import keep getting this error:
`Imported Az MicroBurst functions
Imported AzureAD MicroBurst functions
Import-Module : Could not load type 'Microsoft.Azure.Management.DataLake.Analytics.Models.DataLakeStoreAccountInfo'
from assembly 'Microsoft.Azure.Management.DataLake.Analytics, Version=3.0.0.0, Culture=neutral,
PublicKeyToken=31bf3856ad364e35'.
At C:\Program Files\WindowsPowerShell\Modules\AzureRM.DataLakeAnalytics\4.2.3\AzureRM.DataLakeAnalytics.psm1:21 char:1
+ Import-Module (Join-Path -Path $PSScriptRoot -ChildPath Microsoft.Azu ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Import-Module], TypeLoadException
    + FullyQualifiedErrorId : System.TypeLoadException,Microsoft.PowerShell.Commands.ImportModuleCommand

Import-Module : The module to process 'AzureRM.DataLakeAnalytics.psm1', listed in field 'ModuleToProcess/RootModule'
of module manifest 'C:\Program
Files\WindowsPowerShell\Modules\AzureRM.DataLakeAnalytics\4.2.3\AzureRM.DataLakeAnalytics.psd1' was not processed
because no valid module was found in any module directory.
At C:\Program Files\WindowsPowerShell\Modules\AzureRM\5.7.0\AzureRM.psm1:30 char:1
+ Import-Module AzureRM.DataLakeAnalytics -RequiredVersion 4.2.3 -Globa ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (AzureRM.DataLakeAnalytics:String) [Import-Module], PSInvalidOperat
   ionException
    + FullyQualifiedErrorId : Modules_ModuleFileNotFound,Microsoft.PowerShell.Commands.ImportModuleCommand

MSOnline module not installed, checking other modules
Imported Misc MicroBurst functions
Imported Azure REST API MicroBurst functions`

**Comment by kfosaaen** [comment]
It looks like you have some AzureRM modules installed in your test environment. Please let me know if this interferes with your ability to use any of the functions.

**Comment by DarknightCanada** [comment]
Thank you for your reply! I installed Az Powershell and  AzureAD. Many modules does not work including Get-AzPasswords

thanks
