### ISSUE TITLE
Missing misc functions import-module

### ISSUE THREAD

**Issue by jeffbencteux** [NetSPI/MicroBurst#21]
Not all of the ps1 scripts included in the "misc" folders are automatically loaded when importing MicroBurst's main psm1 file:

https://github.com/NetSPI/MicroBurst/blob/156c4e9f4253b482b2b68eda4651116b9f0f2e17/Misc/MicroBurst-Misc.psm1#L1-L6

I had the issue when trying to run "Get-AzureVMExtensionSettings". Is that a wanted behaviour or should they be added to the above list?

**Comment by kfosaaen** [comment]
The "Get-AzureVMExtensionSettings" is intentionally not included in the imported module functions as it's supposed to be used directly on an Azure VM. I can update the usage on the function to better reflect that.
