### ISSUE TITLE
Very slow on big environment

### ISSUE THREAD

**Issue by quentinhardy** [NetSPI/MicroBurst#22]
Hello,

Thank you for this very useful tool.

I tried to get users, groups, devices with the command "Get-AzDomainInfo".
I worked on a big environment with 80 000 users, 40 000 groups, etc.

It takes much time to get users, but I had to stop the step when the tool searches groups of each user.
After 15 hours, this step was not yet finished.

Best regards,

**Comment by isaac-banda** [comment]
Hello,
 I also tried to run "Get-AzDomainInfo" and it has been running for hours while showing the message, "WARNING: This cmdlet is using API version beta which is under preview". See picture below.
 
I would be glad to learn a workaround to this problem. 

<img width="469" alt="MicroBurst-warning" src="https://user-images.githubusercontent.com/110998750/183957824-f990e59a-cbf0-436f-984e-56606cead20f.png">

**Comment by kfosaaen** [comment]
This is a known issue with larger environments. To help, do the user and groups collection separate from the subscription dumping. You can toggle the Users and Groups with Y/N values in the command.

We'll address the API issues in the other issue.
