### ISSUE TITLE
Get-AzDomaininfo throwing an API version-related warning

### ISSUE THREAD

**Issue by isaac-banda** [NetSPI/MicroBurst#23]
Hello,
 I also tried to run "Get-AzDomainInfo" and it has been running for hours while showing the message, "WARNING: This cmdlet is using API version beta which is under preview". See picture below.
 I am using Windows 10 Pro. The version of my Windows PowerShell is shown in the picture below.
 
I would be glad to learn a workaround to this problem. 

<img width="469" alt="MicroBurst-warning" src="https://user-images.githubusercontent.com/110998750/183957824-f990e59a-cbf0-436f-984e-56606cead20f.png">

<img width="398" alt="PowerShell-Version" src="https://user-images.githubusercontent.com/110998750/183959599-2d2c9450-c612-46ea-a17b-0a2a7b310794.png">

_Originally posted by @isaac-banda in https://github.com/NetSPI/MicroBurst/issues/22#issuecomment-1210924417_

**Comment by kfosaaen** [comment]
I have adjusted the WarningAction preference on the offending commands and fixed it with this commit - https://github.com/NetSPI/MicroBurst/commit/b5d5f37bd416241c1d87e63a6eb2d4c6e38b15e7
