### ISSUE TITLE
Get-AzureADServicePrincipal: Could not load file or assembly 'RestSharp

### ISSUE THREAD

**Issue by faheemadam** [NetSPI/MicroBurst#32]
Get-AzureADServicePrincipal: Could not load file or assembly 'RestSharp, Version=106.3.1.0, Culture=neutral, PublicKeyToken=598062e77f915f75'. Could not find or load a specific file. (0x80131621)

any idea how i can fix this error

**Comment by kfosaaen** [comment]
Can you show what commands you're running that are generating this error?
