### ISSUE TITLE
Module Checking Logic Flaws

### ISSUE THREAD

**Issue by init5-SF** [NetSPI/MicroBurst#35]
Hello,

The module checking logic in MicroBurst.psm1 has some issues.

If AzureAD module is not pre-installed on the system, the below code will not load the local version from $PSScriptRoot
PowerShell will simply throw an error and will immediately go to the CATCH statement, so you end up without loading anything, neither the installed module (if any) nor the local version
`Import-Module AzureAD -ErrorAction Stop`
`Import-Module $PSScriptRoot\AzureAD\MicroBurst-AzureAD.psm1`

Here's what the result looks like:
![image](https://github.com/NetSPI/MicroBurst/assets/10214861/ebdbd099-020f-4eae-8c22-f5782852034a)

My test machine has Az and AzureAD pre-installed, so what happens is:
- Az/AzureAD get imported using the `Import-Module AzureAD -ErrorAction Stop`
- Then they are imported again from the local version, since first import didn't throw errors so the code doesn't stop
- MSOnline throws an error coz I don't have it installed, however, the local version never gets loaded coz the code jumps to the CATCH statement

The module checking logic should be something like this
```
if (!(Get-Module AzureAD)) {
   if (Get-InstalledModule -Name AzureAD -ErrorAction SilentlyContinue) { 
      Write-Host -ForegroundColor Green "Found AzureAD installed, Importing." 
      Import-Module AzureAD
   }
   else {
      Write-Host -ForegroundColor Green "AzureAD not installed, Importing local version."
      Import-Module $PSScriptRoot\AzureAD\MicroBurst-AzureAD.psm1
   }
}
```

Cheers & thanks for the nice tool!

**Comment by kfosaaen** [comment]
I think there's some confusion on what you're defining as the "local module version", or I might be misunderstanding the issue, but the "MicroBurst-AzureAD.psm1" file just imports the ps1 functions in the AzureAD folder. Those ps1 functions rely on having the AzureAD module installed.
