### ISSUE TITLE
Conflicting Modules 

### ISSUE THREAD

**Issue by init5-SF** [NetSPI/MicroBurst#36]
MicroBurst won't run on recent versions of PowerShell

This is all instances where MicroBurst will attempt to install modules online
![image](https://github.com/NetSPI/MicroBurst/assets/10214861/a8739a04-829e-4678-bd02-b4e89d179b5f)

Unfortunately some of these modules can never coexist together anymore. This what I get:
![image](https://github.com/NetSPI/MicroBurst/assets/10214861/8a32be05-00b7-4b8f-8880-5376c6334815)

After some digging I found this:
![image](https://github.com/NetSPI/MicroBurst/assets/10214861/60701080-309c-40c3-bedd-4d9b3536a545)
Reference: https://learn.microsoft.com/en-us/powershell/azure/troubleshooting?view=azps-11.2.0#az-and-azurerm-coexistence

I guess the tool needs to be re-written so that it no longer relies on either Azure or AzureRM modules.
AzureAD, Az, MSOnline should be sufficient.

**Comment by kfosaaen** [comment]
I just [updated the module import file](https://github.com/NetSPI/MicroBurst/commit/a168c53be7b57e64ca85f4eea6805572a53dc490) to remove the AzureRM imports. Those were actually deprecated in the toolset a long time ago, so it doesn't make sense to import them by default. Thanks!

**Comment by init5-SF** [comment]
Super! Thanks for the fast response.
I think Azure module is no longer maintained as well, is it still needed for Microburst?
