### ISSUE TITLE
Cannot find Get-AzDomainInfo function

### ISSUE THREAD

**Issue by rick-engle** [NetSPI/MicroBurst#38]
Hello, I imported the MicroBurst PowerShell module using Import-Module .\MicroBurst.psm1 but it seems to be missing the Get-AzDomainInfo function. The only thing close that seems available after the import is Get-AzDomainInfoREST.
Any idea what might be wrong?

Thanks!
  Rick

**Comment by kfosaaen** [comment]
Are you using the latest version of the code? I just did a test module import on my system and the function was available.

**Comment by rick-engle** [comment]
Hi @kfosaaen I should have responded earlier but I did find out what was going on that didn't seem to be super clear from the readme for MicroBurst.   I went back and before importing the MicroBurst PS module made sure that I first installed these Azure PowerShell modules:  
##  Recommended Modules to install:
##  Az
##  AzureAd
##  MSOnline

Once I had all of those modules pre-installed then the MicroBurst installer revealed all of the functions, I wanted to use including AzDomainInfo.

Thanks,
  Rick
