### ISSUE TITLE
MicroBurst running on Kali Linux

### ISSUE THREAD

**Issue by manotux** [NetSPI/MicroBurst#39]
Hello, are there any plans or at least interest in making MicroBurst compatible with PowerShell on Kali Linux?

I've been experimenting with it a bit, but before proceeding further, I would like to know if there is any background information on this topic. 

Thanks for the great tool.

**Comment by manotux** [comment]
Hello Karl,

I have been experimenting with it and had some success in a few modules so far. Unfortunately I'm not an experienced developer to ensure the resulting code with be a refactored multi-platform code following all best practices.

For example, in order to make Invoke-EnumerateAzureSubDomains work, I considered [DnsClient-PS](https://github.com/rmbolger/DnsClient-PS) as requirement rather than DnsClient, but the resulting code now works only on PS Core ...

Anyway, if at some point I get any function multi-platform I'll create a PR.

Thanks

**Comment by kfosaaen** [comment]
Thanks for looking into it! I know the certificate generation for Automation Account extraction in Get-AzPasswords will also be a pain point. Feel free to reach out if you want any input.
