### ISSUE TITLE
Installation Issues

### ISSUE THREAD

**Issue by dariansaric** [NetSPI/MicroBurst#4]
Hi, I'm having a huge issue importing the base module.
PS C:\Users\****\Downloads\MicroBurst-master> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      6.1.3
PSEdition                      Core
GitCommitId                    6.1.3
OS                             Microsoft Windows 10.0.14393
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

Here is the otuput:
PS C:\Users\****\Downloads\MicroBurst-master> Import-Module .\MicroBurst.psm1
VERBOSE: Loading module from path 'C:\Users\****\Downloads\MicroBurst-master\Get-AzureDomainInfo.ps1'.
VERBOSE: Dot-sourcing the script file 'C:\Users\****\Downloads\MicroBurst-master\Get-AzureDomainInfo.ps1'.

Confirm
Are you sure you want to perform this action?
Performing the operation "Install-Module" on target "Version '6.13.1' of module 'AzureRM'".
[Y] Yes  [A] Yes to All  [N] No  [L] No to All  [S] Suspend  [?] Help (default is "Y"): A

Untrusted repository
You are installing the modules from an untrusted repository. If you trust this repository, change its
InstallationPolicy value by running the Set-PSRepository cmdlet. Are you sure you want to install the modules from
'PSGallery'?
[Y] Yes  [A] Yes to All  [N] No  [L] No to All  [S] Suspend  [?] Help (default is "N"): A

Confirm
Are you sure you want to perform this action?
Performing the operation "Install-Module" on target "Version '5.3.0' of module 'Azure'".
[Y] Yes  [A] Yes to All  [N] No  [L] No to All  [S] Suspend  [?] Help (default is "Y"): A

Untrusted repository
You are installing the modules from an untrusted repository. If you trust this repository, change its InstallationPolicy value by running the
Set-PSRepository cmdlet. Are you sure you want to install the modules from 'PSGallery'?
[Y] Yes  [A] Yes to All  [N] No  [L] No to All  [S] Suspend  [?] Help (default is "N"): A
VERBOSE: Loading module from path 'C:\Users\****\Downloads\MicroBurst-master\Get-AzurePasswords.ps1'.
VERBOSE: Dot-sourcing the script file 'C:\Users\****\Downloads\MicroBurst-master\Get-AzurePasswords.ps1'.
Import-Module : Could not load file or assembly 'System.Windows.Forms, Version=4.0.0.0, 
Culture=neutral, PublicKeyToken=b77a5c561934e089'. The system cannot find the file specified.
At C:\Program Files\PowerShell\Modules\AzureRM.Profile\5.8.2\AzureRM.Profile.psm1:81 char:1
+ Import-Module (Join-Path -Path $PSScriptRoot -ChildPath Microsoft.Azu ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : NotSpecified: (:) [Import-Module], FileNotFoundException
+ FullyQualifiedErrorId : System.IO.FileNotFoundException,Microsoft.PowerShell.Commands.ImportModuleCommand

Import-Module : The module to process 'AzureRM.Profile.psm1', listed in field 'ModuleToProcess/RootModule' of module manifest 'C:\Program Files\PowerShell\Modules\AzureRM.Profile\5.8.2\AzureRM.Profile.psd1' was not processed because no valid module was found in any module directory.
At C:\Program Files\PowerShell\Modules\AzureRM\6.13.1\AzureRM.psm1:81 char:1
+ Import-Module AzureRM.Profile -RequiredVersion 5.8.2 -Global
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : ResourceUnavailable: (AzureRM.Profile:String) [Import-Module], PSInvalidOperationException
+ FullyQualifiedErrorId : Modules_ModuleFileNotFound,Microsoft.PowerShell.Commands.ImportModuleCommand

Import-Module : Could not load file or assembly 'System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'. The sys
tem cannot find the file specified.
At C:\Program Files\PowerShell\Modules\AzureRM.Profile\5.8.2\AzureRM.Profile.psm1:81 char:1
+ Import-Module (Join-Path -Path $PSScriptRoot -ChildPath Microsoft.Azu ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : NotSpecified: (:) [Import-Module], FileNotFoundException
+ FullyQualifiedErrorId : System.IO.FileNotFoundException,Microsoft.PowerShell.Commands.ImportModuleCommand

Import-Module : The module to process 'AzureRM.Profile.psm1', listed in field 'ModuleToProcess/RootModule' of module manifest 'C:\Program Files\PowerShell\Modules\AzureRM.Profile\5.8.2\AzureRM.Profile.psd1' was not processed because no valid module was found in any module directory.
At C:\Program Files\PowerShell\Modules\Azure.Storage\4.6.1\Azure.Storage.psm1:50 char:5
+     Import-Module AzureRM.Profile -MinimumVersion 5.6.0 -Scope Global
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : ResourceUnavailable: (AzureRM.Profile:String) [Import-Module], PSInvalidOperationException
+ FullyQualifiedErrorId : Modules_ModuleFileNotFound,Microsoft.PowerShell.Commands.ImportModuleCommand

Import-Module : Could not load file or assembly 'System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'. The system cannot find the file specified.
At C:\Program Files\PowerShell\Modules\AzureRM.Profile\5.8.2\AzureRM.Profile.psm1:81 char:1
+ Import-Module (Join-Path -Path $PSScriptRoot -ChildPath Microsoft.Azu ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : NotSpecified: (:) [Import-Module], FileNotFoundException
+ FullyQualifiedErrorId : System.IO.FileNotFoundException,Microsoft.PowerShell.Commands.ImportModuleCommand

Import-Module : The module to process 'AzureRM.Profile.psm1', listed in field 'ModuleToProcess/RootModule' of module manifest 'C:\Program Files\PowerShell\Modules\AzureRM.Profile\5.8.2\AzureRM.Profile.psd1' was not processed because no valid module was found in any module directory.
At C:\Program Files\PowerShell\Modules\AzureRM.AnalysisServices\0.6.14\AzureRM.AnalysisServices.psm1:19 char:5
+     Import-Module AzureRM.Profile -MinimumVersion 5.5.1 -Scope Global
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : ResourceUnavailable: (AzureRM.Profile:String) [Import-Module], PSInvalidOperationException
+ FullyQualifiedErrorId : Modules_ModuleFileNotFound,Microsoft.PowerShell.Commands.ImportModuleCommand

Import-Module : Could not load file or assembly 'System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'. The system cannot find the file specified.
At C:\Program Files\PowerShell\Modules\AzureRM.Profile\5.8.2\AzureRM.Profile.psm1:81 char:1
+ Import-Module (Join-Path -Path $PSScriptRoot -ChildPath Microsoft.Azu ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : NotSpecified: (:) [Import-Module], FileNotFoundException
+ FullyQualifiedErrorId : System.IO.FileNotFoundException,Microsoft.PowerShell.Commands.ImportModuleCommand

Import-Module : The module to process 'AzureRM.Profile.psm1', listed in field 'ModuleToProcess/RootModule' of module manifest 'C:\Program Files\PowerShell\Modules\AzureRM.Profile\5.8.2\AzureRM.Profile.psd1' was not processed because no valid module was found in any module directory.
At C:\Program Files\PowerShell\Modules\Azure.AnalysisServices\0.5.4\Azure.AnalysisServices.psm1:19 char:5
+     Import-Module AzureRM.Profile -MinimumVersion 5.4.0 -Scope Global
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : ResourceUnavailable: (AzureRM.Profile:String) [Import-Module], PSInvalidOperationException
+ FullyQualifiedErrorId : Modules_ModuleFileNotFound,Microsoft.PowerShell.Commands.ImportModuleCommand

VERBOSE: Loading module from path 'C:\Users\dsaric1\Downloads\MicroBurst-master\Get-MSOLDomainInfo.ps1'.
VERBOSE: Dot-sourcing the script file 'C:\Users\dsaric1\Downloads\MicroBurst-master\Get-MSOLDomainInfo.ps1'.

Confirm
Are you sure you want to perform this action?
Performing the operation "Install-Module" on target "Version '1.1.183.17' of module 'MSOnline'".
[Y] Yes  [A] Yes to All  [N] No  [L] No to All  [S] Suspend  [?] Help (default is "Y"): A

Untrusted repository
You are installing the modules from an untrusted repository. If you trust this repository, change its InstallationPolicy value by running the
Set-PSRepository cmdlet. Are you sure you want to install the modules from 'PSGallery'?
[Y] Yes  [A] Yes to All  [N] No  [L] No to All  [S] Suspend  [?] Help (default is "N"): A
VERBOSE: Loading module from path 'C:\Users\****\Downloads\MicroBurst-master\Invoke-AzureRmVMBulkCMD.ps1'.
VERBOSE: Dot-sourcing the script file 'C:\Users\****\Downloads\MicroBurst-master\Invoke-AzureRmVMBulkCMD.ps1'.
Import-Module : Could not load file or assembly 'System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'. The system cannot find the file specified.
At C:\Program Files\PowerShell\Modules\AzureRM.Profile\5.8.2\AzureRM.Profile.psm1:81 char:1
+ Import-Module (Join-Path -Path $PSScriptRoot -ChildPath Microsoft.Azu ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : NotSpecified: (:) [Import-Module], FileNotFoundException
+ FullyQualifiedErrorId : System.IO.FileNotFoundException,Microsoft.PowerShell.Commands.ImportModuleCommand

Import-Module : The module to process 'AzureRM.Profile.psm1', listed in field 'ModuleToProcess/RootModule' of module manifest 'C:\Program Files\PowerShell\Modules\AzureRM.Profile\5.8.2\AzureRM.Profile.psd1' was not processed because no valid module was found in any module directory.
At C:\Program Files\PowerShell\Modules\AzureRM\6.13.1\AzureRM.psm1:81 char:1
+ Import-Module AzureRM.Profile -RequiredVersion 5.8.2 -Global
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : ResourceUnavailable: (AzureRM.Profile:String) [Import-Module], PSInvalidOperationException
+ FullyQualifiedErrorId : Modules_ModuleFileNotFound,Microsoft.PowerShell.Commands.ImportModuleCommand

VERBOSE: Loading module from path 'C:\Users\****\Downloads\MicroBurst-master\Invoke-EnumerateAzureBlobs.ps1'.
VERBOSE: Dot-sourcing the script file 'C:\Users\****\Downloads\MicroBurst-master\Invoke-EnumerateAzureBlobs.ps1'.
VERBOSE: Loading module from path 'C:\Users\****\Downloads\MicroBurst-master\Invoke-EnumerateAzureSubDomains.ps1'.
VERBOSE: Dot-sourcing the script file 'C:\Users\****\Downloads\MicroBurst-master\Invoke-EnumerateAzureSubDomains.ps1'.

Does anyone have any idea why this is happening? I've been on this for about 4 days without progress...

**Comment by kfosaaen** [comment]
It looks like you are having issues importing/installing the AzureRM/Azure modules. Try installing them manually from the PS Gallery:
- https://www.powershellgallery.com/packages/AzureRM/6.13.1
- https://www.powershellgallery.com/packages/Azure/5.3.0

**Comment by dariansaric** [comment]
I did as you told me. First I authenticated with 'Connect-AzAccount', then ran the 'Get-AzurePasswords' module. This is the output:

PS C:\Users\****> Connect-AzAccount
WARNING: Both Az and AzureRM modules were detected on this machine. Az and AzureRM modules cannot be imported in the same session or used in
 the same script or runbook. If you are running PowerShell in an environment you control you can use the 'Uninstall-AzureRm' cmdlet to remov
e all AzureRm modules from your machine. If you are running in Azure Automation, take care that none of your runbooks import both Az and Azu
reRM modules. More information can be found here: https://aka.ms/azps-migration-guide

Account        SubscriptionName     TenantId                             Environment
-------        ----------------              --------                             -----------
****                     ****                **************************       AzureCloud 



PS C:\Users\****> Import-Module .\Downloads\MicroBurst-master\MicroBurst.psm1

PS C:\Users\****> Get-AzurePasswords
Get-AzureRmContext : Method 'get_SerializationSettings' in type 'Microsoft.Azure.Management.Internal.Resources.ResourceManagementClient' 
from assembly 'Microsoft.Azure.Commands.ResourceManager.Common, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' does 
not have an implementation.
At C:\Users\****\Downloads\MicroBurst-master\Get-AzurePasswords.ps1:90 char:20
+     $LoginStatus = Get-AzureRmContext
+                    ~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-AzureRmContext], TypeLoadException
    + FullyQualifiedErrorId : System.TypeLoadException,Microsoft.Azure.Commands.Profile.GetAzureRMContextCommand
 
WARNING: No active login. Prompting for login.
WARNING: Login process failed.
Get-AzureRmSubscription : Method 'get_SerializationSettings' in type 
'Microsoft.Azure.Management.Internal.Resources.ResourceManagementClient' from assembly 'Microsoft.Azure.Commands.ResourceManager.Common, 
Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' does not have an implementation.
At C:\Users\****\Downloads\MicroBurst-master\Get-AzurePasswords.ps1:104 char:26
+ ... bscriptions = Get-AzureRmSubscription -WarningAction SilentlyContinue
+                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-AzureRmSubscription], TypeLoadException
    + FullyQualifiedErrorId : System.TypeLoadException,Microsoft.Azure.Commands.Profile.GetAzureRMSubscriptionCommand
 
I figured there was some problem with authenticating with Azure module, so I have tried to authenticate with the AzureRM module:

PS C:\Users\****> Login-AzAccount
Login-AzAccount : Method 'get_SerializationSettings' in type 'Microsoft.Azure.Management.Internal.Resources.ResourceManagementClient' from 
assembly 'Microsoft.Azure.Commands.ResourceManager.Common, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' does not 
have an implementation.
At line:1 char:1
+ Login-AzAccount
+ ~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Connect-AzureRmAccount], TypeLoadException
    + FullyQualifiedErrorId : System.TypeLoadException,Microsoft.Azure.Commands.Profile.ConnectAzureRmAccountCommand

Does anyone know how to resolve this, or should I ask this question on the AzureRM repository FQA?

**Comment by kfosaaen** [comment]
Based off of the errors that you're getting from the Get-AzureRmContext command, I'm guessing something is off with your AzureRM module installation. Try reinstalling the module (as an admin).
