### ISSUE TITLE
MSOnline cmdlet deprecation?

### ISSUE THREAD

**Issue by albert-widjaja** [NetSPI/MicroBurst#41]
Hi Team,

The MSOnline module's obsolete prerequisite was shown in the https://github.com/NetSPI/MicroBurst modules. Will there be an updated version with Microsoft Graph?

Thank you in advance and I look forward to your reply.

**Comment by kfosaaen** [comment]
Technically, it's not a prerequisite module, we just have some functions that can use it if it's available.

At this time we're not looking to do anything with Graph in MicroBurst. I'd point you to some other options for scraping Graph data.

- https://github.com/dafthack/GraphRunner
- https://github.com/dirkjanm/ROADtools

**Comment by albert-widjaja** [comment]
Thank you @kfosaaen for the update.
