### ISSUE TITLE
Get-AzPasswords or Get-Passwords not work

### ISSUE THREAD

**Issue by BuSh1DO** [NetSPI/MicroBurst#8]
Hello

I authenticate with "az login" and "connect-Azure", but when executing anything with the "Get-Passwords" script, PowerShell gives an error:

PS C:\Users\XXXX\Downloads\MicroBurst-master\Az> get-help Get-AzPasswords.ps1
get-help : Get-Help could not find Get-AzPasswords.ps1 in a help file in this session. To download updated help topics type: "Update-Help". To get help online, search for the help topic in the TechNet library at https:/go.microsoft.com/fwlink/?LinkID=107116.
At line:1 char:1
+ get-help Get-AzPasswords.ps1
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (:) [Get-Help], HelpNotFoundException
    + FullyQualifiedErrorId : HelpNotFound,Microsoft.PowerShell.Commands.GetHelpCommand

PS C:\Users\XXXX\Downloads\MicroBurst-master\Az> Get-AzPasswords.ps1 -verbose
Get-AzPasswords.ps1 : The term 'Get-AzPasswords.ps1' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ Get-AzPasswords.ps1 -verbose
+ ~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Get-AzPasswords.ps1:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

PS C:\Users\XXXX\Downloads\MicroBurst-master> Get-AzurePasswords
Get-AzurePasswords : The term 'Get-AzurePasswords' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ Get-AzurePasswords
+ ~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Get-AzurePasswords:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

i've delete/remove all modules, but the problem persist

at this time i've this modules:
Version    Name                                Repository           Description
-------    ----                                ----------           -----------
4.3.0      Az                                  PSGallery            Microsoft Azure PowerShell - Cmdlets to manage resources in Azure. This module is compatible with WindowsPowerShell and PowerShell Core....
1.9.0      Az.Accounts                         PSGallery            Microsoft Azure PowerShell - Accounts credential management cmdlets for Azure Resource Manager in Windows PowerShell and PowerShell Core....
1.1.1      Az.Advisor                          PSGallery            Microsoft Azure PowerShell - Azure Advisor Cmdlets for Advisor in Windows PowerShell and PowerShell Core. Get Advisor recommendations, Manage Advisor configurations.
1.1.2      Az.Aks                              PSGallery            Microsoft Azure PowerShell - Azure managed Kubernetes cmdlets for Windows PowerShell and PowerShell Core....
1.1.3      Az.AnalysisServices                 PSGallery            Microsoft Azure PowerShell - Analysis Services cmdlets for Windows PowerShell and PowerShell Core....
2.0.1      Az.ApiManagement                    PSGallery            Microsoft Azure PowerShell - Api Management service cmdlets for Azure Resource Manager in Windows PowerShell and PowerShell Core....
1.1.0      Az.ApplicationInsights              PSGallery            Microsoft Azure PowerShell - Application Insights management cmdlets for Azure Resource Manager in Windows PowerShell and PowerShell Core.  Creates and manages application insights in Azure Resource ...
1.3.6      Az.Automation                       PSGallery            Microsoft Azure PowerShell - Automation service cmdlets for Azure Resource Manager in Windows PowerShell and PowerShell Core....
3.1.0      Az.Batch                            PSGallery            Microsoft Azure PowerShell - Batch service cmdlets for Azure Resource Manager in Windows PowerShell and PowerShell Core....
1.0.3      Az.Billing                          PSGallery            Microsoft Azure PowerShell - Billing service cmdlets for Azure Resource Manager in Windows PowerShell and PowerShell Core....
1.4.3      Az.Cdn                              PSGallery            Microsoft Azure PowerShell - CDN service cmdlets for Azure Resource Manager in Windows PowerShell and PowerShell Core....
1.5.0      Az.CognitiveServices                PSGallery            Microsoft Azure PowerShell - Cognitive Services management cmdlets for Azure Resource Manager in Windows PowerShell and PowerShell Core. Creates and manages cognitive services accounts in Azure Resou...
4.2.0      Az.Compute                          PSGallery            Microsoft Azure PowerShell - Compute service cmdlets for Azure Resource Manager in Windows PowerShell and PowerShell Core.  Manages virtual machines, hosted services, and related resources in Azure R...
1.0.3      Az.ContainerInstance                PSGallery            Microsoft Azure PowerShell - Container Instance cmdlets for Azure Resource Manager in Windows PowerShell and PowerShell Core....
1.1.1      Az.ContainerRegistry                PSGallery            Microsoft Azure PowerShell - Container Registry service cmdlets for Azure Resource Manager in Windows PowerShell and PowerShell Core....
1.1.0      Az.DataBoxEdge                      PSGallery            Microsoft Azure PowerShell - DataBoxEdge service cmdlets for Azure Resource Manager in Windows PowerShell and PowerShell Core....
1.8.2      Az.DataFactory                      PSGallery            Microsoft Azure PowerShell - Data Factory service cmdlets for Azure Resource Manager in Windows PowerShell and PowerShell Core....
1.0.2      Az.DataLakeAnalytics                PSGallery            Microsoft Azure PowerShell - Data Lake Analytics in Windows PowerShell and PowerShell Core....
1.2.8      Az.DataLakeStore                    PSGallery            Microsoft Azure PowerShell - Azure Data Lake Store cmdlets in Windows PowerShell and PowerShell Core....
1.0.0      Az.DataShare                        PSGallery            Microsoft Azure PowerShell - DataShare service cmdlets for Azure Resource Manager in Windows PowerShell and PowerShell Core.
1.1.0      Az.DeploymentManager                PSGallery            PowerShell .Net Core Microsoft Azure PowerShell - Deployment Manager cmdlets for Azure Resource Manager....
1.0.0      Az.DesktopVirtualization            PSGallery            Microsoft Azure PowerShell: DesktopVirtualization cmdlets
1.0.2      Az.DevTestLabs                      PSGallery            Microsoft Azure PowerShell - DevTest Labs service cmdlets for Azure Resource Manager in Windows PowerShell and PowerShell Core....
1.1.2      Az.Dns                              PSGallery            Microsoft Azure PowerShell - DNS service cmdlets for Azure Resource Manager in Windows PowerShell and PowerShell Core....
1.2.3      Az.EventGrid                        PSGallery            Microsoft Azure PowerShell - Event Grid service cmdlets for Azure Resource Manager in Windows PowerShell and PowerShell Core....
1.5.0      Az.EventHub                         PSGallery            Microsoft Azure PowerShell - Event Hubs service cmdlets for Azure Resource Manager in Windows PowerShell and PowerShell Core....
1.5.0      Az.FrontDoor                        PSGallery            Microsoft Azure PowerShell - Front Door service cmdlets for Azure Resource Manager in Windows PowerShell and PowerShell Core....
1.0.1      Az.Functions                        PSGallery            Microsoft Azure PowerShell - Azure Functions service cmdlets for Azure Resource Manager in Windows PowerShell and PowerShell Core....
3.3.0      Az.HDInsight                        PSGallery            Microsoft Azure PowerShell - HDInsight service cmdlets for Azure Resource Manager in Windows PowerShell and PowerShell Core....
1.1.0      Az.HealthcareApis                   PSGallery            Microsoft Azure PowerShell - HealthcareApis management cmdlets for Azure Resource Manager in Windows PowerShell and PowerShell Core. Creates and manages HealthcareApis service accounts in Azure Resou...
2.5.0      Az.IotHub                           PSGallery            Microsoft Azure PowerShell - IoT Hub service cmdlets for Azure Resource Manager in Windows PowerShell and PowerShell Core....
2.0.0      Az.KeyVault                         PSGallery            Microsoft Azure PowerShell - Key Vault service cmdlets for Azure Resource Manager in Windows PowerShell and PowerShell Core....
1.3.2      Az.LogicApp                         PSGallery            Microsoft Azure PowerShell - Logic Apps cmdlets for Azure Resource Manager in Windows PowerShell and PowerShell Core....
1.1.3      Az.MachineLearning                  PSGallery            Microsoft Azure PowerShell - Machine Learning Web Services cmdlets for Azure Resource Manager in Windows PowerShell and PowerShell Core....
1.0.0      Az.Maintenance                      PSGallery            Microsoft Azure PowerShell - Maintenance cmdlets for Azure Resource Manager in Windows PowerShell and PowerShell Core....
1.0.2      Az.ManagedServices                  PSGallery            Microsoft Azure PowerShell - ManagedServices cmdlets for Azure Resource Manager
1.0.2      Az.MarketplaceOrdering              PSGallery            Microsoft Azure PowerShell - Marketplace Ordering agreements service cmdlets for Azure Resource Manager in Windows PowerShell and PowerShell Core....
1.1.1      Az.Media                            PSGallery            Microsoft Azure PowerShell - Media service cmdlets for Azure Resource Manager in Windows PowerShell and PowerShell Core....
2.0.1      Az.Monitor                          PSGallery            Microsoft Azure PowerShell - Monitor service cmdlets for Azure Resource Manager in Windows PowerShell and PowerShell Core....
3.1.0      Az.Network                          PSGallery            Microsoft Azure PowerShell - Networking service cmdlets for Azure Resource Manager in Windows PowerShell and PowerShell Core....
1.1.1      Az.NotificationHubs                 PSGallery            Microsoft Azure PowerShell - Notification Hubs cmdlets for Azure Resource Manager in Windows PowerShell and PowerShell Core....
2.2.0      Az.OperationalInsights              PSGallery            Microsoft Azure PowerShell - Operational Insights service cmdlets for Azure Resource Manager in Windows PowerShell and PowerShell Core.
1.3.1      Az.PolicyInsights                   PSGallery            Microsoft Azure PowerShell - Azure Policy Insights cmdlets for Windows PowerShell and PowerShell Core. Allows querying policy evaluation events and compliance states....
1.1.2      Az.PowerBIEmbedded                  PSGallery            Microsoft Azure PowerShell - Power BI Embedded service management cmdlets for Azure Resource Manager in Windows PowerShell and PowerShell Core.  Creates and manages Power BI Embedded workspace collec...
1.0.3      Az.PrivateDns                       PSGallery            Microsoft Azure PowerShell - Private DNS service cmdlets for Azure Resource Manager in Windows PowerShell and PowerShell Core....
2.10.0     Az.RecoveryServices                 PSGallery            Microsoft Azure PowerShell - Recovery Services cmdlets for Azure Resource Manager in Windows PowerShell and PowerShell Core....
1.2.1      Az.RedisCache                       PSGallery            Microsoft Azure PowerShell - Redis Cache service cmdlets for Azure Resource Manager in Windows PowerShell and PowerShell Core....
1.0.3      Az.Relay                            PSGallery            Microsoft Azure PowerShell - Relay service cmdlets for Azure Resource Manager in Windows PowerShell and PowerShell Core....
2.2.0      Az.Resources                        PSGallery            Microsoft Azure PowerShell - Azure Resource Manager and Active Directory cmdlets in Windows PowerShell and PowerShell Core.  Manages subscriptions, tenants, resource groups, deployment templates, pro...
1.4.1      Az.ServiceBus                       PSGallery            Microsoft Azure PowerShell - Service Bus service cmdlets for Azure Resource Manager in Windows PowerShell and PowerShell Core....
2.1.0      Az.ServiceFabric                    PSGallery            Microsoft Azure PowerShell - Service Fabric cmdlets for Azure Resource Manager in Windows PowerShell and PowerShell Core....
1.1.1      Az.SignalR                          PSGallery            Microsoft Azure PowerShell - Azure SignalR service commands for Windows PowerShell and PowerShell Core....
2.8.0      Az.Sql                              PSGallery            Microsoft Azure PowerShell - SQL service cmdlets for Azure Resource Manager in Windows PowerShell and PowerShell Core....
1.1.0      Az.SqlVirtualMachine                PSGallery            Microsoft Azure PowerShell - SqlVirtualMachine service cmdlets for Azure Resource Manager in Windows PowerShell and PowerShell Core.
2.2.0      Az.Storage                          PSGallery            Microsoft Azure PowerShell - Storage service data plane and management cmdlets for Azure Resource Manager in Windows PowerShell and PowerShell Core.  Creates and manages storage accounts in Azure Res...
1.2.3      Az.StorageSync                      PSGallery            Microsoft Azure PowerShell - Storage Sync cmdlets in Windows PowerShell and PowerShell Core. Manages operations pertaining to Azure File Sync in PowerShell.
1.0.1      Az.StreamAnalytics                  PSGallery            Microsoft Azure PowerShell - Stream Analytics service cmdlets for Azure Resource Manager in Windows PowerShell and PowerShell Core....
1.0.0      Az.Support                          PSGallery            Microsoft Azure PowerShell - Azure Support cmdlets for Azure Resource Manager in Windows PowerShell and PowerShell Core.
1.0.4      Az.TrafficManager                   PSGallery            Microsoft Azure PowerShell - Traffic Manager service cmdlets for Azure Resource Manager in Windows PowerShell and PowerShell Core....
1.10.0     Az.Websites                         PSGallery            Microsoft Azure PowerShell - App Service (Web Apps) service cmdlets for Azure Resource Manager in Windows PowerShell and PowerShell Core....
5.3.0      Azure                               PSGallery            Microsoft Azure PowerShell - Service Management
4.6.1      Azure.Storage                       PSGallery            Microsoft Azure PowerShell - Storage service cmdlets. Manages blobs, queues, tables and files in Microsoft Azure storage accounts
2.0.2.76   AzureAD                             PSGallery            Azure Active Directory V2 General Availability Module....
6.13.1     AzureRM                             PSGallery            Azure Resource Manager Module
0.6.14     AzureRM.AnalysisServices            PSGallery            Microsoft Azure PowerShell - Analysis Services
6.1.7      AzureRM.ApiManagement               PSGallery            Microsoft Azure PowerShell - Api Management service cmdlets for Azure Resource Manager
0.1.8      AzureRM.ApplicationInsights         PSGallery            Microsoft Azure PowerShell - Application Insights service management cmdlets for Azure Resource Manager.  Creates and manages application insights in Azure Resource Manager.
6.1.1      AzureRM.Automation                  PSGallery            Microsoft Azure PowerShell - Automation service cmdlets for Azure Resource Manager
4.0.11     AzureRM.Backup                      PSGallery            Microsoft Azure PowerShell - Azure Backup service cmdlets for Azure Resource Manager
4.1.5      AzureRM.Batch                       PSGallery            Microsoft Azure PowerShell - Batch service cmdlets for Azure Resource Manager
0.14.6     AzureRM.Billing                     PSGallery            Microsoft Azure PowerShell - Billing service cmdlets for Azure Resource Manager
5.0.6      AzureRM.Cdn                         PSGallery            Microsoft Azure PowerShell - CDN service cmdlets for Azure Resource Manager
0.9.12     AzureRM.CognitiveServices           PSGallery            Microsoft Azure PowerShell - Cognitive Services management cmdlets for Azure Resource Manager. Creates and manages cognitive services accounts in Azure Resource Manager.
5.9.1      AzureRM.Compute                     PSGallery            Microsoft Azure PowerShell - Compute service cmdlets for Azure Resource Manager.  Manages virtual machines, hosted services, and related resources in Azure Resource Manager
0.3.7      AzureRM.Consumption                 PSGallery            Microsoft Azure PowerShell - Consumption service cmdlets for Azure Resource Manager
0.2.12     AzureRM.ContainerInstance           PSGallery            Microsoft Azure PowerShell - Container Instance cmdlets for Azure Resource Manager
1.0.10     AzureRM.ContainerRegistry           PSGallery            Microsoft Azure PowerShell - ContainerRegistry service cmdlets for Azure Resource Manager
5.0.3      AzureRM.DataFactories               PSGallery            Microsoft Azure PowerShell - DataFactories service cmdlets for Azure Resource Manager
0.5.11     AzureRM.DataFactoryV2               PSGallery            Microsoft Azure PowerShell - DataFactories service cmdlets for Azure Resource Manager
5.1.4      AzureRM.DataLakeAnalytics           PSGallery            Microsoft Azure PowerShell - Data Lake Analytics
6.2.1      AzureRM.DataLakeStore               PSGallery            Microsoft Azure PowerShell - Data Lake Store
4.0.9      AzureRM.DevTestLabs                 PSGallery            Microsoft Azure PowerShell - DevTestLabs service cmdlets for Azure Resource Manager
5.1.0      AzureRM.Dns                         PSGallery            Microsoft Azure PowerShell - Dns service cmdlets for Azure Resource Manager
0.3.7      AzureRM.EventGrid                   PSGallery            Microsoft Azure PowerShell - EventGrid service cmdlets for Azure Resource Manager
0.7.0      AzureRM.EventHub                    PSGallery            Microsoft Azure PowerShell - EventHubs service cmdlets for Azure Resource Manager
4.1.8      AzureRM.HDInsight                   PSGallery            Microsoft Azure PowerShell - HDInsight service cmdlets for Azure Resource Manager
5.1.5      AzureRM.Insights                    PSGallery            Microsoft Azure PowerShell - Insights service cmdlets for Azure Resource Manager
3.1.8      AzureRM.IotHub                      PSGallery            Microsoft Azure PowerShell - IotHub service cmdlets for Azure Resource Manager
5.2.1      AzureRM.KeyVault                    PSGallery            Microsoft Azure PowerShell - KeyVault service cmdlets for Azure Resource Manager
4.1.4      AzureRM.LogicApp                    PSGallery            Microsoft Azure PowerShell - LogicApp cmdlets for Azure Resource Manager
0.18.5     AzureRM.MachineLearning             PSGallery            Microsoft Azure PowerShell - Machine Learning Web Services cmdlets for Azure Resource Manager
0.4.8      AzureRM.MachineLearningCompute      PSGallery            Microsoft Azure PowerShell - Machine Learning Compute cmdlets for Azure Resource Manager
0.2.7      AzureRM.MarketplaceOrdering         PSGallery            Microsoft Azure PowerShell - MarketplaceOrdering agreements service cmdlets for Azure Resource Manager
0.10.4     AzureRM.Media                       PSGallery            Microsoft Azure PowerShell - Media service cmdlets for Azure Resource Manager
6.11.1     AzureRM.Network                     PSGallery            Microsoft Azure PowerShell - Network service cmdlets for Azure Resource Manager
5.0.3      AzureRM.NotificationHubs            PSGallery            Microsoft Azure PowerShell - NotificationHubs
5.0.6      AzureRM.OperationalInsights         PSGallery            Microsoft Azure PowerShell - OperationalInsights service cmdlets for Azure Resource Manager
1.1.0      AzureRM.PolicyInsights              PSGallery            Microsoft Azure PowerShell - Azure Policy Insights cmdlets. Allows querying policy evaluation events and compliance states.
4.1.10     AzureRM.PowerBIEmbedded             PSGallery            Microsoft Azure PowerShell - Power BI Embedded service management cmdlets for Azure Resource Manager.  Creates and manages Power BI Embedded workspace collections and Power BI Dedicated Capacities in...
5.8.2      AzureRM.profile                     PSGallery            Microsoft Azure PowerShell - Profile credential management cmdlets for Azure Resource Manager
4.1.9      AzureRM.RecoveryServices            PSGallery            Microsoft Azure PowerShell - RecoveryServices cmdlets for Azure Resource Manager
4.5.2      AzureRM.RecoveryServices.Backup     PSGallery            Microsoft Azure PowerShell - Azure Backup service cmdlets for Azure Resource Manager
0.2.12     AzureRM.RecoveryServices.SiteRec... PSGallery            Microsoft Azure PowerShell - SiteRecovery service cmdlets for Azure Resource Manager
5.1.0      AzureRM.RedisCache                  PSGallery            Microsoft Azure PowerShell - RedisCache service cmdlets for Azure Resource Manager
0.3.12     AzureRM.Relay                       PSGallery            Microsoft Azure PowerShell - Relay service cmdlets for Azure Resource Manager
6.7.3      AzureRM.Resources                   PSGallery            Microsoft Azure PowerShell - Azure Resource Manager cmdlets.  Manages subscriptions, tenants, resource groups, deployment templates, providers, and resource permissions in Azure Resource Manager.  Pr...
0.16.10    AzureRM.Scheduler                   PSGallery            Microsoft Azure PowerShell - Scheduler cmdlets for Azure Resource Manager
0.6.13     AzureRM.ServiceBus                  PSGallery            Microsoft Azure PowerShell - ServiceBus service cmdlets for Azure Resource Manager
0.3.15     AzureRM.ServiceFabric               PSGallery            Microsoft Azure PowerShell - Service Fabric cmdlets for Azure Resource Manager
1.0.0      AzureRM.SignalR                     PSGallery            Microsoft Azure PowerShell - Azure SignalR service commands
4.12.1     AzureRM.Sql                         PSGallery            Microsoft Azure PowerShell - Sql service cmdlets for Azure Resource Manager
5.2.0      AzureRM.Storage                     PSGallery            Microsoft Azure PowerShell - Storage service management cmdlets for Azure Resource Manager.  Creates and manages storage accounts in Azure Resource Manager.
4.0.10     AzureRM.StreamAnalytics             PSGallery            Microsoft Azure PowerShell - StreamAnalytics service cmdlets for Azure Resource Manager
4.0.5      AzureRM.Tags                        PSGallery            Microsoft Azure PowerShell - Tags service cmdlets for Azure Resource Manager
4.1.3      AzureRM.TrafficManager              PSGallery            Microsoft Azure PowerShell - TrafficManager service cmdlets for Azure Resource Manager
4.0.5      AzureRM.UsageAggregates             PSGallery            Microsoft Azure PowerShell - UsageAggregates service cmdlets for Azure Resource Manager
5.2.0      AzureRM.Websites                    PSGallery            Microsoft Azure PowerShell - Websites service cmdlets for Azure Resource Manager
1.1.183.57 MSOnline                            PSGallery            Microsoft Azure Active Directory Module for Windows PowerShell

can you help?

**Comment by BuSh1DO** [comment]
commands like "C:\MicroBurst-master\MicroBurst-master> Get-AzADGroup" works and give output


SecurityEnabled : False
MailNickname    : RespoXXXXXXXX@XXXXXXXXXXX
ObjectType      : Group
Description     : RespoXXXXXXXXXXXXXXXXX
DisplayName     : RespXXXXXXXXXXXXXXXXXXX
Id              : XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
Type            :

**Comment by kfosaaen** [comment]
Hi BuSh1DO,
Did you run `Import-Module .\MicroBurst.psm1` first? Or are you just using the local execution of the PS script?
The tool is meant to be imported as a module, then run.

**Comment by BuSh1DO** [comment]
> 
> 
> Hi BuSh1DO,
> Did you run `Import-Module .\MicroBurst.psm1` first? Or are you just using the local execution of the PS script?
> The tool is meant to be imported as a module, then run.

Hi,

i've import module but the error persist

**Comment by kfosaaen** [comment]
Based off the errors, I'm guessing something is going wrong on the module import. 
Can you try importing the individual Az MicroBurst Modules (Import-module .\Az\MicroBurst-Az.psm1)?
