### ISSUE TITLE
Get-AzureDomainInfo.ps1 InvalidOperation: (:) [], RuntimeException

### ISSUE THREAD

**Issue by AlucardsSandvich** [NetSPI/MicroBurst#9]
Hi,
Just to start off, very impressive tool.

However, when reaching the "Getting Domain Users for each group..." prompt when running Get-AzureDomainInfo I seem to be facing this error 

You cannot call a method on a null-valued expression.
At Get-AzDomainInfo.ps1:213 char:42
+ ... each ($char in $charlist){$groupName = $groupName.replace($char,'.')}
+                               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

Seems to hang for a good while; little unsure 

The command I've ran is:
 Get-AzDomainInfo -folder C:\Users\testbox\Desktop\test -Verbose

Any ideas what may be the cause of this? Has anyone encountered this before?

**Comment by kfosaaen** [comment]
Do you have any groups in the test environment?
My guess is that your $groupLists variable (line 208) is empty and the error line that you have is trying to replace invalid characters on an empty set.
I can add a catch there for empty groups, but just want to check with your environment first.

**Comment by kfosaaen** [comment]
If it's just hanging on that section, it might just be struggling on a specific group name. Are you still getting group members exported to CSV files in the Groups folder?
